### ISSUE TITLE
무기폼 변경패스 오타

### ISSUE THREAD

**Issue by SZ1Ikazuchi** [gesori-pro/PSO2ENPatchCSV#209]
![2020-10-19_23-19-33_Off (2)](https://user-images.githubusercontent.com/73165204/96563507-fb2cae00-12fc-11eb-8174-844d89a87aff.png)

폼이 푬으로 쓰인 곳 하나 있음
아이템 랩에서 무기 '푬' 변경을 할 수 있다

**Comment by gesori-pro** [comment]
오우야 ㄳㄳ
