### ISSUE TITLE
아이템 번역 오류

### ISSUE THREAD

**Issue by SZ1Ikazuchi** [gesori-pro/PSO2ENPatchCSV#210]
![2020-11-08_20-54-20-690_Off (2)](https://user-images.githubusercontent.com/73165204/98464220-c4173180-2204-11eb-8cf9-dac761d89a8c.png)]
돈없어서 사서 확인은 못해봤는데, 에스 레픽스 아이템에서 설명은 남성 체조복으로 되어있음.

**Comment by gesori-pro** [comment]
오타임 ㄳ
