### ISSUE TITLE
아이템 "S7 추가:휘쟁의 혜"

### ISSUE THREAD

**Issue by Miksya** [gesori-pro/PSO2ENPatchCSV#211]
![화면 캡처 2020-11-11 233339](https://user-images.githubusercontent.com/30250543/98824202-5d00b380-2476-11eb-8fa9-7450775b2628.jpg)
휘정의 혜 오타?

**Comment by gesori-pro** [comment]
휘정 오타맞음 수정했음 ㄳㄳ
