### ISSUE TITLE
(질문)아예 번역도 안된 에피소드들 있음?

### ISSUE THREAD

**Issue by SZ1Ikazuchi** [gesori-pro/PSO2ENPatchCSV#212]
스토리퀘스트 두세개 정도면 돌면서 대본은 만들수 있는데
파일 건드리는쪽으로 참여는 못함

**Comment by gesori-pro** [comment]
스토리 담당 번역가가 지금 다른 게임 번역 작업중이라 좀 걸린다고 함
그래서 이제 NPC오더나 대사 번역을 해야할 거 같음

**Comment by focuslite** [comment]
스토리 담당 번역가가 지금 다른 게임 번역 작업중이라 좀 걸린다고 함
그래서 이제 NPC오더나 대사 번역을 해야할 거 같음

**Comment by focuslite** [comment]
스토리 담당 번역가가 지금 다른 게임 번역 작업중이라 좀 걸린다고 함
그래서 이제 NPC오더나 대사 번역을 해야할 거 같음

**Comment by focuslite** [comment]
스토리 담당 번역가가 지금 다른 게임 번역 작업중이라 좀 걸린다고 함
그래서 이제 NPC오더나 대사 번역을 해야할 거 같음

**Comment by SZ1Ikazuchi** [comment]
이렇게 첨부하는거 맞는지 모르겠는데, NPC마토이 대사 번역해봄.
도움되는거 맞으면 한두명씩 번역해옴

[MatoiNPCHassan.txt](https://github.com/focuslite/PSO2ENPatchCSV/files/5551741/MatoiNPCHassan.txt)

**Comment by gesori-pro** [comment]
https://onedrive.live.com/view.aspx?resid=1F12CE5624E551AE!14030&ithint=file%2cpptx&authkey=!AO24jM9BePW-GK4

이거 한번 참조해보샘

**Comment by SZ1Ikazuchi** [comment]
진행중임 ㄳ
