### ISSUE TITLE
타임어택 퀘스트 "주파연습 리리빠"

### ISSUE THREAD

**Issue by Miksya** [gesori-pro/PSO2ENPatchCSV#214]
![image](https://user-images.githubusercontent.com/30250543/99877370-0a2ab700-2c41-11eb-8ebc-e28965d2f333.png)
중요한건 아닌데 리리파 같아서 올려봄

**Comment by gesori-pro** [comment]
수정하겟음 ㄳ

**Comment by gesori-pro** [comment]
고쳣슴
