### ISSUE TITLE
S4:천휘의 수호 오류

### ISSUE THREAD

**Issue by SZ1Ikazuchi** [gesori-pro/PSO2ENPatchCSV#215]
![2020-12-02_22-42-48-362_Off (2)](https://user-images.githubusercontent.com/73165204/100880270-df1d4e80-34ef-11eb-8977-38b2757ac239.png)

이름이 시류의 용이랑 붙어있음

**Comment by gesori-pro** [comment]
오 쉣 수정하겟음

**Comment by gesori-pro** [comment]
수정햇음 ㄳ
