### ISSUE TITLE
지하 갱도 카라신 vs 갱도 카라신

### ISSUE THREAD

**Issue by Miksya** [gesori-pro/PSO2ENPatchCSV#217]
![화면 캡처 2020-12-19 142010](https://user-images.githubusercontent.com/30250543/102681552-8e069d80-4205-11eb-911b-c983bd67bf87.jpg)
왼쪽은 퀘스트, 오른쪽은 요리 재료들

**Comment by gesori-pro** [comment]
오늘중으로 수정하겟음 ㄳ

**Comment by gesori-pro** [comment]
게을러서 오늘햇음
