### ISSUE TITLE
레벨 업 메시지 )

### ISSUE THREAD

**Issue by Miksya** [gesori-pro/PSO2ENPatchCSV#221]
![화면 캡처 2021-05-29 003025](https://user-images.githubusercontent.com/30250543/120010688-65869900-c018-11eb-9cec-a96de8d69e70.jpg)

**Comment by Miksya** [comment]
닉네임 )님이 n레벨이 되었습니다.

**Comment by gesori-pro** [comment]
오우 쉣 수정하겟음

**Comment by gesori-pro** [comment]
수정했음 ㄳㄳ
