### ISSUE TITLE
번역 제보 issue #1

### ISSUE THREAD

**Issue by medraud94** [gesori-pro/PSO2ENPatchCSV#225]
호시와타리 - 별을 잇는자의 번역 부분에 대한 제보입니다.
호시와타리(星渡り)는 현대 일본어가 아니라 옛 일본어의 동사의 명사화로 해석해야 하는 단어입니다.
平家物語　七・忠度都落
「ただ今の御わたりこそ、情けもすぐれて深う、あはれもことに思ひ知られて」
헤이케모노가타리에서 사용된 와타리는 "내방" "방문"의 존칭으로 사용되고 있습니다.
伊勢物語　三一
[古]むかし、宮の内にて、ある御達の局の前をわたりけるに
이세모노가타리에서 와타리는 "지나간다"의 존칭어로 사용되고 있습니다. 
계속, 잇다와 비슷한 용법은
大和物語　六
人の妻にてありける人に、しのびて逢ひわたりけるを
야마토모노가타리에서 "행동을 계속하고 있다"라는 용도로 사용된 것이 전부입니다.
즉 별을 잇는자라는 번역은 먼저, 별을 잇는 자(띄어쓰기)도 지켜야 하지만, 의미적으로도 옳지 않은 번역으로 사료됩니다.

**Comment by gesori-pro** [comment]
어떤 단어가 가장 적절할까요

**Comment by medraud94** [comment]
정답은 없다고 봅니다만, 별을 건너는 자는 좀 딱딱한 직역이겠죠. 별을 잇는 자는 pso2와 ngs의 관계에서 나온 의역인 것 같습니다만, 아무래도 상당히 의미가 떨어져 있어 제보드렸습니다.

**Comment by medraud94** [comment]
제 부족한 생각으로는 "별나들이" "별나드리' 정도밖에 생각나지 않네요. 너무 의역이라 좀 그렇습니다만.

**Comment by gesori-pro** [comment]
사실 별을 건너는 자가 제일 낫긴한데 내부에서 반대했는데 그냥 별을 건너는 자로 할까 싶슴다

**Comment by medraud94** [comment]
결국 좋은 번역은 언제나 어감이 문제니까요... 사람 더 많은 데서 투표나 공모해보는 것도 좋을 성 싶습니다. 
파일 좀 들쑤숴봤는데, 돗치-샌듯치는 돗치 통일이 더 낫지 않을까요?

**Comment by gesori-pro** [comment]
돗치가 어디쪽에 있죠

**Comment by medraud94** [comment]
어 잘못적었군요. 몬스터 이름 돗츠,  샌듯츠입니다

**Comment by gesori-pro** [comment]
샌돗츠로 변경하긴했데 어떻게 샌돗츠를 아셨는진 모르겠지만 아직 개발 중 데이터일거에요
