### ISSUE TITLE
그래픽 옵션에 표시 캐릭터 수 설명 오탈자

### ISSUE THREAD

**Issue by lobsterlifer** [gesori-pro/PSO2ENPatchCSV#226]
![image](https://user-images.githubusercontent.com/86040709/123403357-a8ba3480-d5e3-11eb-8c94-cbb3fe52a843.png)
![image](https://user-images.githubusercontent.com/86040709/123403427-ba9bd780-d5e3-11eb-92e0-6d0234c22115.png)

수치를 내리면/낮추면 처리가 다소 가벼워집니다 인 것 같은데 오타가있네요.
내리면과 낮추면도 같은 단어로 통일하는게 좋을 것 같아요.

**Comment by lobsterlifer** [comment]
그리고 스샷에 나온김에 얘기하자면 갑자기 긴급 메세지에 전투력 부분이 이상하게 나오는데 이것도 번역 오류인가 싶어요.

**Comment by gesori-pro** [comment]
해당 옵션 부분은 해결했고 전투력 부분은 
![image](https://user-images.githubusercontent.com/29522474/123404775-28480380-d5e4-11eb-8c90-2a09ca39fb1a.png)

해당 사진처럼 잘 나오는 것 보면 오류같네요
