### ISSUE TITLE
핸드액션 グー 의 번역이 잘못되어 있어요.

### ISSUE THREAD

**Issue by Artean2825** [gesori-pro/PSO2ENPatchCSV#227]
핸드액션이 주먹을 쥐는 것을 보면 가위바위보 할 때 주먹을 쥐다라는 의미에서 ぐう인데,
배고플 때 나는 소리의 ぐう로 인식이 되었는지 꼬르륵으로 되어있어요.

**Comment by gesori-pro** [comment]
수정했슴다
